### ISSUE TITLE
Exception if non-existent probe name is included in the config

### ISSUE THREAD

**Issue by h0pbeat** [OpenSensing/funf-core-android#3]
Should be gracefully ignored.

```
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime: FATAL EXCEPTION: main
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime: Process: org.opensensing.opensensingdemo, PID: 13466
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime: java.lang.RuntimeException: Unable to create service edu.mit.media.funf.FunfManager: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.toString()' on a null object reference
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:2835)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at android.app.ActivityThread.access$1800(ActivityThread.java:156)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1434)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:211)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5389)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.toString()' on a null object reference
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at edu.mit.media.funf.config.SingletonTypeAdapterFactory$SingletonTypeAdapter.read(SingletonTypeAdapterFactory.java:113)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at com.google.gson.Gson.fromJson(Gson.java:755)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at com.google.gson.Gson.fromJson(Gson.java:819)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at com.google.gson.Gson.fromJson(Gson.java:792)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at edu.mit.media.funf.FunfManager.requestData(FunfManager.java:543)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at edu.mit.media.funf.FunfManager.requestData(FunfManager.java:535)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at edu.mit.media.funf.pipeline.BasicPipeline.onCreate(BasicPipeline.java:179)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at edu.mit.media.funf.FunfManager.registerPipeline(FunfManager.java:493)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at edu.mit.media.funf.FunfManager.reload(FunfManager.java:220)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at edu.mit.media.funf.FunfManager.reload(FunfManager.java:189)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at edu.mit.media.funf.FunfManager.onCreate(FunfManager.java:170)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:2825)
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at android.app.ActivityThread.access$1800(ActivityThread.java:156) 
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1434) 
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:211) 
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5389) 
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) 
10-07 17:14:30.197 13466-13466/org.opensensing.opensensingdemo E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```

**Comment by h0pbeat** [comment]
Fixed in 57ca1da9b5535d3470f9a1b095712e764cf5affa
